import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Nav from '~/components/layouts/Nav';
import Footer from '~/components/layouts/Footer';
import SidePage from '~/components/layouts/SidePage';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SuryaDev Blog',
  description: 'Generated by Next Js 13',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className + ' flex flex-col min-h-screen bg-teal-200'}
      >
        <Nav />
        <main className="flex-1 container grid grid-cols-1 lg:grid-cols-3 gap-y-8 lg:gap-x-8">
          <section className="col-span-2">{children}</section>
          <SidePage />
        </main>
        <Footer />
      </body>
    </html>
  );
}
